name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - dev

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies and Build
        run: |
          yarn install
          yarn build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GWO_ORG }}'
          channelId: live
          projectId: gwo-org
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
